# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Project/ZYNQ/7035/test2023/test2023.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0.xci
# IP: The module: 'design_1_axi_gpio_7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/ZYNQ/7035/test2023/test2023.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_7_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/ZYNQ/7035/test2023/test2023.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/ZYNQ/7035/test2023/test2023.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Project/ZYNQ/7035/test2023/test2023.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0.xci
# IP: The module: 'design_1_axi_gpio_7_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Project/ZYNQ/7035/test2023/test2023.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/ZYNQ/7035/test2023/test2023.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/Project/ZYNQ/7035/test2023/test2023.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_7_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
