# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/first.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_1_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_1/design_1_axi_gpio_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_1 || ORIG_REF_NAME==design_1_axi_gpio_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_2/design_1_axi_gpio_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_2 || ORIG_REF_NAME==design_1_axi_gpio_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_1/design_1_system_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_1 || ORIG_REF_NAME==design_1_system_ila_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_D_trig_0_0/design_1_D_trig_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_D_trig_0_0 || ORIG_REF_NAME==design_1_D_trig_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_D_trig_0_1/design_1_D_trig_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_D_trig_0_1 || ORIG_REF_NAME==design_1_D_trig_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_FM_0/design_1_system_ila_FM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_FM_0 || ORIG_REF_NAME==design_1_system_ila_FM_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DAC8830_WR_0_0/design_1_DAC8830_WR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DAC8830_WR_0_0 || ORIG_REF_NAME==design_1_DAC8830_WR_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DAC8830_spi_0_0/design_1_DAC8830_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DAC8830_spi_0_0 || ORIG_REF_NAME==design_1_DAC8830_spi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DAC8830_WR_0_1/design_1_DAC8830_WR_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DAC8830_WR_0_1 || ORIG_REF_NAME==design_1_DAC8830_WR_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DAC8830_spi_0_1/design_1_DAC8830_spi_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DAC8830_spi_0_1 || ORIG_REF_NAME==design_1_DAC8830_spi_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_FM_2/design_1_system_ila_FM_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_FM_2 || ORIG_REF_NAME==design_1_system_ila_FM_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MOV_VPP_TOP_0_0/design_1_MOV_VPP_TOP_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_MOV_VPP_TOP_0_0 || ORIG_REF_NAME==design_1_MOV_VPP_TOP_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MOV_VPP_TOP_1_0/design_1_MOV_VPP_TOP_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_MOV_VPP_TOP_1_0 || ORIG_REF_NAME==design_1_MOV_VPP_TOP_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_D_trig_0_2/design_1_D_trig_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_D_trig_0_2 || ORIG_REF_NAME==design_1_D_trig_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_VPP_0/design_1_system_ila_VPP_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_VPP_0 || ORIG_REF_NAME==design_1_system_ila_VPP_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_3/design_1_axi_gpio_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_3 || ORIG_REF_NAME==design_1_axi_gpio_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_AM_0/design_1_system_ila_AM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_AM_0 || ORIG_REF_NAME==design_1_system_ila_AM_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FREQ_counter_0_0/design_1_FREQ_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FREQ_counter_0_0 || ORIG_REF_NAME==design_1_FREQ_counter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FREQ_counter_0_1/design_1_FREQ_counter_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FREQ_counter_0_1 || ORIG_REF_NAME==design_1_FREQ_counter_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clock_1M_0_0/design_1_clock_1M_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clock_1M_0_0 || ORIG_REF_NAME==design_1_clock_1M_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LTC2248_0_0/design_1_LTC2248_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LTC2248_0_0 || ORIG_REF_NAME==design_1_LTC2248_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_3_0/design_1_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_0 || ORIG_REF_NAME==design_1_axi_gpio_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_3_1/design_1_axi_gpio_3_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_3_1 || ORIG_REF_NAME==design_1_axi_gpio_3_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_5_0/design_1_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_5_0 || ORIG_REF_NAME==design_1_axi_gpio_5_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FREQ_counter_FM_0/design_1_FREQ_counter_FM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FREQ_counter_FM_0 || ORIG_REF_NAME==design_1_FREQ_counter_FM_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_6_0/design_1_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_6_0 || ORIG_REF_NAME==design_1_axi_gpio_6_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PSK_OUT_0_0/design_1_PSK_OUT_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PSK_OUT_0_0 || ORIG_REF_NAME==design_1_PSK_OUT_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_7_0/design_1_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_7_0 || ORIG_REF_NAME==design_1_axi_gpio_7_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_DATA_SELE_0_0/design_1_DATA_SELE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_DATA_SELE_0_0 || ORIG_REF_NAME==design_1_DATA_SELE_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_VPP_1/design_1_system_ila_VPP_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_VPP_1 || ORIG_REF_NAME==design_1_system_ila_VPP_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AM_DM_0_0/design_1_AM_DM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AM_DM_0_0 || ORIG_REF_NAME==design_1_AM_DM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MOV_RMS_0_1/design_1_MOV_RMS_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_MOV_RMS_0_1 || ORIG_REF_NAME==design_1_MOV_RMS_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MOV_RMS_AM_0/design_1_MOV_RMS_AM_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_MOV_RMS_AM_0 || ORIG_REF_NAME==design_1_MOV_RMS_AM_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_MOV_RMS_FM_1/design_1_MOV_RMS_FM_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_MOV_RMS_FM_1 || ORIG_REF_NAME==design_1_MOV_RMS_FM_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_FM_DM_0_0/design_1_FM_DM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_FM_DM_0_0 || ORIG_REF_NAME==design_1_FM_DM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PSK_DM_0_0/design_1_PSK_DM_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_PSK_DM_0_0 || ORIG_REF_NAME==design_1_PSK_DM_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AD5664_WR_0_0/design_1_AD5664_WR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AD5664_WR_0_0 || ORIG_REF_NAME==design_1_AD5664_WR_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AD5664_spi_0_0/design_1_AD5664_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AD5664_spi_0_0 || ORIG_REF_NAME==design_1_AD5664_spi_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_SELE_0/design_1_system_ila_SELE_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_SELE_0 || ORIG_REF_NAME==design_1_system_ila_SELE_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# XDC: d:/Project/ZYNQ/7035/test2023/test2023.gen/sources_1/bd/design_1/design_1_ooc.xdc
