// Copyright (C) 1991-2013 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II 64-Bit Version 13.1 (Build Build 162 10/23/2013)
// Created on Sun Apr 20 11:19:50 2025

MOV_AVR MOV_AVR_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.din(din_sig) ,	// input [DIN_WIDTH-1:0] din_sig
	.din_valid(din_valid_sig) ,	// input  din_valid_sig
	.avg_signal(avg_signal_sig) ,	// output [DIN_WIDTH-1:0] avg_signal_sig
	.ac_signal(ac_signal_sig) ,	// output [DIN_WIDTH-1:0] ac_signal_sig
	.ac_signal_valid(ac_signal_valid_sig) 	// output  ac_signal_valid_sig
);

defparam MOV_AVR_inst.N = 1024;
defparam MOV_AVR_inst.DIN_WIDTH = 12;
