# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/constraints/D2023.xdc

# XDC: new/TOP_new.xdc

# IP: ip/dist_mem_gen_Q/dist_mem_gen_Q.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dist_mem_gen_Q || ORIG_REF_NAME==dist_mem_gen_Q} -quiet] -quiet
