# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_I/dist_mem_gen_I.xci
# IP: The module: 'dist_mem_gen_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_I/dist_mem_gen_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_I'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_I/dist_mem_gen_I.xci
# IP: The module: 'dist_mem_gen_I' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_I/dist_mem_gen_I_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dist_mem_gen_I'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
