@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Aug 05 01:47:24 +0800 2023
REM SW Build 3526262 on Mon Apr 18 15:48:16 MDT 2022
REM
REM IP Build 3524634 on Mon Apr 18 20:55:01 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim testbench_am_behav -key {Behavioral:sim_1:Functional:testbench_am} -tclbatch testbench_am.tcl -protoinst "protoinst_files/bd_f60c.protoinst" -protoinst "protoinst_files/bd_36cd.protoinst" -protoinst "protoinst_files/bd_ac61.protoinst" -protoinst "protoinst_files/bd_6de0.protoinst" -protoinst "protoinst_files/bd_a0b7.protoinst" -protoinst "protoinst_files/bd_d860.protoinst" -protoinst "protoinst_files/bd_6076.protoinst" -log simulate.log"
call xsim  testbench_am_behav -key {Behavioral:sim_1:Functional:testbench_am} -tclbatch testbench_am.tcl -protoinst "protoinst_files/bd_f60c.protoinst" -protoinst "protoinst_files/bd_36cd.protoinst" -protoinst "protoinst_files/bd_ac61.protoinst" -protoinst "protoinst_files/bd_6de0.protoinst" -protoinst "protoinst_files/bd_a0b7.protoinst" -protoinst "protoinst_files/bd_d860.protoinst" -protoinst "protoinst_files/bd_6076.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
