# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tfgg484-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/clk_wiz_0
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/ila_0
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_I
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/mult_gen_0
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_ph
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/ila_1
    c:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_Q
  } {
      D:/XILINX/Vivado/2019.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/XILINX/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/clk_wiz_0
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/ila_0
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_I
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/mult_gen_0
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_ph
    C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/ila_1
    c:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/ip/dist_mem_gen_Q
  } {
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/dist_mem_gen_Q_stub.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/clk_wiz_0_stub.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/ila_0_stub.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/dist_mem_gen_I_stub.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/mult_gen_0_stub.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/dist_mem_ph_stub.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/realtime/ila_1_stub.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/two_channel_ADC.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/filter/CIC_decimation_10_fs6MHz.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/Demodulate.srcs/sources_1/new/TOP_new.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/filter/CIC_decimation_20_fs36MHz.v
      C:/Users/86183/Desktop/dianSai/2019_G/Vivado/FM_audio_demodulate/src/two_channel_dac.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/Phase_dev_cal.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/demod/Demodulate.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/demod/Cordic.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/demod/IQ_generate.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/filter/LPF_60k_fs1_8MHz.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/filter/LPF_20kHz_fs1_8MHz.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/TOP_FSM.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/Max_Min.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/Get_Ma.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/FSM_Max_Min.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/Judge_and_calculate.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/SquareJudge.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/Signal_discrim.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/DAC_selector.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/Message_generator.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/Fre_Judge.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/ASK_decision.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/AGC.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/cal/Find_Max_Lim.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/AM_DC_Isolator.v
      C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/src/Communicate.v
    }
      rt::read_vhdl -lib xpm D:/XILINX/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top TOP_new
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/86183/Desktop/dianSai/2023_D/Vivado/Demodulate/Demodulate/.Xil/Vivado-2568-LAPTOP-59026BCA/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
